openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Получить список пользователей
      responses:
        "200":
          description: Успешный ответ
  /users/{id}:
    get:
      summary: Получить информацию о пользователе по ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID пользователя
          schema:
            type: integer
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: John Doe
        "404":
          description: Пользователь не найден
